### PR TITLE
Enable Strict Concurrency Checking

### LINKED ISSUE #103: Complete Concurrency Checking
### Problem

With [Swift 6 approaching in a few months](https://forums.swift.org/t/swift-6-0-release-process/70220) and [nightly builds already being available](https://forums.swift.org/t/swift-6-0-nightly-development-snapshots/70936) we should ensure that all our packages are working well with all Swift concurrency checks.

### Solution

[Enable strict concurrency checking](https://www.swift.org/documentation/concurrency/) in the Swift Package in a PR and ensure that we don't have any warnings remaining in the packages as we develop new features or fix bugs from now.

The UI Testing App target should also enable [Enable strict concurrency checking](https://www.swift.org/documentation/concurrency/).

The corresponding PR should fix all related warnings when enabling strict concurrency checking.

### Additional context

We should consider adding `SWIFT_TREAT_WARNINGS_AS_ERRORS = YES` to our general workflows to ensure all warnings are flagged as errors during our CI setup.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct and Contributing Guidelines

### PR DESCRIPTION
**Pull request by pauljohanneskraft**
# Enable Strict Concurrency Checking

## :recycle: Current situation & Problem
Fixes #103

## :gear: Release Notes 
- Enables Strict Concurrency Checking to prepare for the upcoming Swift 6 changes

## :books: Documentation
No documentation changes needed, since strict concurrency checking does not emit any warnings and therefore does not require any changes to the actual implementation.

## :white_check_mark: Testing
No additional tests needed, since the changes should only trigger more warnings by the compiler and otherwise not change anything.

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by pauljohanneskraft** [comment]
I opened this PR first to confirm that these are the intended changes or get feedback on whether you would like to have this set up a different way. If this is the intended way, I can then open PRs to all the other Spezi components.

**Comment by PSchmiedmayer** [comment]
@pauljohanneskraft Thank you for taking a look at this!!

Two things I am wondering and would love to get your and others input @StanfordSpezi/developers:
1. It seems like the changes do create some warnings that we would address before a PR is merged, e.g.: https://github.com/StanfordSpezi/Spezi/actions/runs/8943078512/job/24570618361?pr=104. Is there a way that we can enforce warnings as errors to ensure that all warnings are addressed before PRs are merged?
2. I think it would also make sense to enable strict concurrency checking in the Xcode project of the UI testing application to validate that we don't run into any warnings when using the types (which sometimes seems to be the case when using the APIs, e.g., missing Sendable conformance).

Would be great to get your thoughts on both ideas and how we might be able to do this here and in other PRs.

**Review by PSchmiedmayer — COMMENTED** [review]
@pauljohanneskraft Thank you for taking a look at this!!

Two things I am wondering and would love to get your and others input @StanfordSpezi/developers:
1. It seems like the changes do create some warnings that we would address before a PR is merged, e.g.: https://github.com/StanfordSpezi/Spezi/actions/runs/8943078512/job/24570618361?pr=104. Is there a way that we can enforce warnings as errors to ensure that all warnings are addressed before PRs are merged?
2. I think it would also make sense to enable strict concurrency checking in the Xcode project of the UI testing application to validate that we don't run into any warnings when using the types (which sometimes seems to be the case when using the APIs, e.g., missing Sendable conformance).

Would be great to get your thoughts on both ideas and how we might be able to do this here and in other PRs.

**Comment by pauljohanneskraft** [comment]
I totally agree with 2, we should add it to the UI testing project as well. There, it would probably be configured in the xcodeproj, rather than being provided by the Package.swift file.

Regarding 1, I haven't yet had the chance to have a look at the CI configuration - if you want, I can have a look.

**Comment by PSchmiedmayer** [comment]
Thank you for the improvements @pauljohanneskraft! Thank you for resolving 2). 

I would propose the merge strategy and testing detailed in https://github.com/StanfordSpezi/.github/pull/50 to get this PR merged, address all the warnings to check that merge checks switch to green when they are resolved and then merge the PRs in the proposed order.

**Review by PSchmiedmayer — CHANGES_REQUESTED** [review]
Thank you for the improvements @pauljohanneskraft! Thank you for resolving 2). 

I would propose the merge strategy and testing detailed in https://github.com/StanfordSpezi/.github/pull/50 to get this PR merged, address all the warnings to check that merge checks switch to green when they are resolved and then merge the PRs in the proposed order.

**Comment by PSchmiedmayer** [comment]
Closed after we have updated the CI and setup in #108

**Pull request closed without merging**
